# Workspaces con nombres (puede dejarse aquí o en monitors)
workspace = 1, name:Iris
workspace = 2, name:Alice
workspace = 3, name:Eve
workspace = 4, name:Ayre
workspace = 5, name:cirel
workspace = 9, name:Hide

##########################
# Variables y alias útiles
##########################
# Variables para reutilizar rutas o apps
$term = kitty
$menu = wofi --show drun
$browser = google-chrome-stable
$filemanager = thunar

# Comando seguro para bloqueo
$lock = swaylock -f -c 000000

##########################
# Variables de entorno
##########################
env = PATH,$PATH:$scrPath
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = MOZ_ENABLE_WAYLAND,1
env = GDK_SCALE,1